// src/app/layout.js
import Header from "@/components/Navbar/Navbar.jsx";
import "./globals.css";
import Footer from "@/components/Footer/Footer.jsx";

export const metadata = {
  title: "Anaya Dream Trip",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (<>

    <html lang="en">
      <body>
      <Header />
        {children}
        <Footer />
      </body>
    </html>
    </>
  );
}
