// src/app/layout.js
import Header from "@/Components/Navbar/Header";
import "./globals.css";
import Footer from "@/Components/Footer/Footer";
import "leaflet/dist/leaflet.css";

export const metadata = {
  title: "Anaya Dream Trip",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (<>

    <html lang="en">
      <body>
      <Header />
        {children}
        <Footer/>
      </body>
    </html>
    </>
  );
}
